### ISSUE TITLE
GetUuidEntryFromUuid raises UnboundLocalError when self.uuid_entries is empty

### ISSUE THREAD

**Issue by joachimmetz** [ydkhatri/UnifiedLogReader#15]
https://github.com/ydkhatri/UnifiedLogReader/blob/db0242344143055da7a33e8bbe8e1e2293c08c14/UnifiedLog/Lib.py#L1445

when self.uuid_entries is empty and GetUuidEntryFromUuid is called it raises `UnboundLocalError: local variable 'b' referenced before assignment`

What is the expected behavior? To raise KeyError or return None, or equiv?

To do:

* [x] ~~Have GetUuidEntryFromUuid return None~~
* [x] remove GetUuidEntryFromUuid
  * pending https://github.com/joachimmetz/UnifiedLogReader/tree/clean1

**Comment by ydkhatri** [comment]
This function is no longer used. The last time `return b` should replaced with return None, to fix the issue. That is be the expected behavior.

**Comment by joachimmetz** [comment]
Ack I change that in the PR

**Comment by joachimmetz** [comment]
Issue addressed
