### ISSUE TITLE
Dsc.Parse returns True if file can be opened but data fails to parse

### ISSUE THREAD

**Issue by joachimmetz** [ydkhatri/UnifiedLogReader#16]
The exception in Dsc.Parse at https://github.com/ydkhatri/UnifiedLogReader/blob/master/UnifiedLog/Lib.py#L1504 does not sets the result to False hence the method returns True even if the code between the try except fails.

Also the Except is very broad and will catch things like ImportErrors, could you reduce the except to IOError, OSError, and struct related exceptions?

**Comment by joachimmetz** [comment]
I've made some changes in https://github.com/ydkhatri/UnifiedLogReader/pull/14/commits/14c40873ca315fbafae672396c3acc79ccf0ddfd#diff-f76a8f6cff79cdf7dd95a5aebd1a729bR125 for the broad except. See if you agree.

**Comment by joachimmetz** [comment]
@ydkhatri I'm having a look at refactoring the Parse method

An FYI https://github.com/ydkhatri/UnifiedLogReader/blob/master/UnifiedLog/Lib.py#L1369

```
            for i in range(self.num_range_entries):
                uuid_index, v_off, data_offset, data_len = struct.unpack("<IIII", buffer[pos:pos+16])
                self.range_entries.append([uuid_index, v_off, data_offset, data_len])
                pos += 16
```
there is no sanity check on `self.num_range_entries` and if this value is large `range(self.num_range_entries)` consumes vast amount of memory. See https://github.com/google/binplist/issues/8 for a similar issue.

**Comment by joachimmetz** [comment]
https://github.com/joachimmetz/UnifiedLogReader/tree/fix16

**Comment by ydkhatri** [comment]
Currently, there aren't many sanity checks in the code, we should add a few to fix at least some of the predictable failures due to file corruption.

**Comment by joachimmetz** [comment]
Agree; thought this can sometimes be tricky to determine what the exact bounds should be, limiting the use of range() will prevent memory consumption to explode.

**Comment by joachimmetz** [comment]
Immediate issue has been addressed.
