### ISSUE TITLE
Dsc.ReadFmtStringAndEntriesFromVirtualOffset inconsistent return type on error and on success

### ISSUE THREAD

**Issue by joachimmetz** [ydkhatri/UnifiedLogReader#17]
Dsc.ReadFmtStringAndEntriesFromVirtualOffset returns a string on error and a tuple on success

https://github.com/ydkhatri/UnifiedLogReader/blob/master/UnifiedLog/Lib.py#L1442

Please clarify what the return value should be. Or should this method raise on error instead?

**Comment by ydkhatri** [comment]
That is a bug. It should raise an exception, which will get caught here-
[https://github.com/ydkhatri/UnifiedLogReader/blob/db0242344143055da7a33e8bbe8e1e2293c08c14/UnifiedLog/Lib.py#L1075](https://github.com/ydkhatri/UnifiedLogReader/blob/db0242344143055da7a33e8bbe8e1e2293c08c14/UnifiedLog/Lib.py#L1075)
I will need to add that error message in the exception block as `format_str = '<compose failure [UUID]>'`

**Comment by joachimmetz** [comment]
I opt to make the necessary changes in or after https://github.com/ydkhatri/UnifiedLogReader/pull/14

**Comment by joachimmetz** [comment]
FYI the places where ReadFmtStringAndEntriesFromVirtualOffset  is used there is already have a `try ... except` and don't seem to use the result of method on exception.

**Comment by joachimmetz** [comment]
Changes made https://github.com/ydkhatri/UnifiedLogReader/pull/14/commits/a3ebd1adb690c6ac9a6f22114a6d3f98dec90eef

**Comment by ydkhatri** [comment]
> FYI the places where ReadFmtStringAndEntriesFromVirtualOffset is used there is already have a `try ... except` and don't seem to use the result of method on exception.

Correct. Hence my comment about that-
> I will need to remove that string return and add that error message in the exception block as `format_str = '<compose failure [UUID]>'`

**Comment by joachimmetz** [comment]
ack, I've made changes in https://github.com/ydkhatri/UnifiedLogReader/pull/14 let me know if that does not correspond with what you had in mind

**Comment by joachimmetz** [comment]
issue addressed
