### ISSUE TITLE
DecompressTraceV3Log not used?

### ISSUE THREAD

**Issue by joachimmetz** [ydkhatri/UnifiedLogReader#23]
@ydkhatri going over the code to add more test coverage it looks like:

scripts/UnifiedLogReader.py defines DecompressTraceV3Log but this function is not used
this means that the DecompressTraceV3 function in UnifiedLog/Lib.py is also not used.

Could you confirm if my assessment is correct? And if there is additional context I'm not aware of, why these functions should remain in the code base. Otherwise I'll prep a PR to remove them.

**Comment by joachimmetz** [comment]
Another function in UnifiedLog/Lib.py that do not appear to be used is DebugPrintTSRead

**Comment by ydkhatri** [comment]
Yes, they are not used (decompress functions), but I would keep them just for reference. 
You should remove the DebugPrintTSRead function though.

**Comment by joachimmetz** [comment]
Ack, thx I've created https://github.com/ydkhatri/UnifiedLogReader/pull/24 to address the stale DebugPrintTSRead

**Comment by joachimmetz** [comment]
Question answered
