### ISSUE TITLE
Some errors on a `log collect`-ed archive in macOS 10.14.6

### ISSUE THREAD

**Issue by jp-sentinel** [ydkhatri/UnifiedLogReader#32]
Hello,

First, thank you for the great work ! It's amazing, it should help us a lot to parse logs in Windows.

After some try, most of the logs are extracted, but we still have some errors. I didn't open a ticket for each one, but I can if needed. Are they known ? Each one are repeated a bunch of times at different frequency, with different address / offset / values.

```
ERROR - missing data for log @ 0x4F0E8
```

```
Traceback (most recent call last):
  File "UnifiedLogReader-master/UnifiedLog/tracev3_file.py", line 674, in RecreateMsgFromFmtStringAndData
    msg += self._ReadNtSid(raw_data)
  File "UnifiedLogReader-master/UnifiedLog/data_format.py", line 76, in _ReadNtSid
    sub_authorities = struct.unpack('<{}I'.format(num_sub_auth), data[8:8*num_sub_auth])
error: unpack requires a string argument of length 4
```

```
UnifiedLogReader-master/UnifiedLog/tracev3_file.py:662: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if unk == 'D': # 0x44
UnifiedLogReader-master/UnifiedLog/tracev3_file.py:667: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif unk == '#': #0x23
```

```
ERROR - Unknown value for mbr_details found 0xa3 in log @ 0x16C18E8
```

```
ERROR - Data Reference not found for unique_ref=0x1000003535BF4D626 ct=3656559941158!
```

```
ERROR - Failed to open file system_logs.logarchive/94/D581CA04CA3AA78087D09B74E2AB67
Traceback (most recent call last):
  File "UnifiedLogReader-master/UnifiedLog/virtual_file.py", line 31, in open
IOError: [Errno 24] Too many open files: 'system_logs.logarchive/94/D581CA04CA3AA78087D09B74E2AB67'
```

```
ERROR - Did not read data of type 3, t1=location, t2=_CLDaemonStatusStateTrackerState, length=0x28 from log @ 0x5D18 ct=25128227678
ERROR - Did not read data of type 3, t1=location, t2=_CLLocationManagerStateTrackerState, length=0x48 from log @ 0x61560 ct=46065225628
ERROR - Did not read data of type 2, t1=AppStoreDaemon, t2=LogPushConnection, length=0x2E from log @ 0x7C1048 ct=15495190668348
```

```
ERROR - Invalid bounds 0x8F1500 for bc166f11-dd33-32af-af67-de0b2c985aa8
```

```
INFO - Unknown custom data object type '{public, location:_CLLocationManagerStateTrackerState}' data size=0x48 in log @ 0x1CE798
```

**Comment by ydkhatri** [comment]
There are a few different issues here. Some of the errors are normal because the logs will contain some entries which are invalid or missing data/metadata. These are the "Invalid bounds.." errors. Some logs reference custom data types which the parser does not know about, hence the "Unknown custom data.." or "Did not read data of type .." messages.

The "Data Reference not found" errors are due to us not knowing the order of parsing of files.

The Unicode errors are due to python2. The script will be released as python3 pretty soon, and that should take care of that.

The errors with `Traceback` are script errors. In this case it's a "Too many open files" error. This should not happen normally. If it is possible to submit the log files for debugging, please do and I can look into why these are happening.

**Comment by ydkhatri** [comment]
If you don't wish to publicly post the file here, send me the files in an email.

**Comment by jp-sentinel** [comment]
@ydkhatri Thank you for the look up. I will send you a log archive (not the same, but with same kind of errors) by email (depending of the size I might give you a Google Drive link).

**Comment by jp-sentinel** [comment]
@ydkhatri Thank you for your reply.

> There are a few different issues here. Some of the errors are normal because the logs will contain some entries which are invalid or missing data/metadata. These are the "Invalid bounds.." errors.

Do you know why it happens ? Is it the normal working of log archives (perhaps because of some pruning, etc ?)

> Some logs reference custom data types which the parser does not know about, hence the "Unknown custom data.." or "Did not read data of type .." messages.

Do you plan to add more data type in your script ? (I'm not sure how much it's complex, I didn't dig deeply your code).

> The "Data Reference not found" errors are due to us not knowing the order of parsing of files.

Is it resolvable ? How the macOS Console is able to know this order ? That being said, the amount of this error is limited, so it can perhaps make sense to track those cases to try to solve them later, as your script walk into next data…

> The Unicode errors are due to python2. The script will be released as python3 pretty soon, and that should take care of that.

👍

> The errors with `Traceback` are script errors. In this case it's a "Too many open files" error. This should not happen normally. If it is possible to submit the log files for debugging, I can look into why these are happening.

For others potentially interested: I sent you an archive, and you are not reproducing. So it's perhaps related to some max open file defaults…

**Comment by ydkhatri** [comment]
> > There are a few different issues here. Some of the errors are normal because the logs will contain some entries which are invalid or missing data/metadata. These are the "Invalid bounds.." errors.
> 
> Do you know why it happens ? Is it the normal working of log archives (perhaps because of some pruning, etc ?)

That and perhaps some other processes like libraries changing or disappearing from the system (via system/program updates). Those error messages will be seen even when you use Apple's `log` utility. I have used the exact same error message strings too! Console hides them from you.

**Comment by ydkhatri** [comment]
> > Some logs reference custom data types which the parser does not know about, hence the "Unknown custom data.." or "Did not read data of type .." messages.
> 
> Do you plan to add more data type in your script ? (I'm not sure how much it's complex, I didn't dig deeply your code).

Eventually yes, but it is low priority right now. 

> > The "Data Reference not found" errors are due to us not knowing the order of parsing of files.
> 
> Is it resolvable ? How the macOS Console is able to know this order ? That being said, the amount of this error is limited, so it can perhaps make sense to track those cases to try to solve them later, as your script walk into next data…

Yes it is resolvable, but this is also low priority right now primarily due to the small number of messages and also because it is mostly debug data, not usually useful for forensics.

**Comment by ydkhatri** [comment]
I just updated the code for python3. Shortly I will update Pypi and also have a windows exe, hopefully sometime today or this weekend.
