### ISSUE TITLE
Custom specifier can be larger than 64 characters

### ISSUE THREAD

**Issue by joachimmetz** [ydkhatri/UnifiedLogReader#35]
Note that the custom specifier can be larger than 64 characters e.g. `%{public,signpost.telemetry:number1,name=SOSSignpostNameSOSCCEnsurePeerRegistration}d`

64 is a limit that is used in https://github.com/ydkhatri/UnifiedLogReader/blob/9bfa5be781ff179c16d7519ef23b080937f3b780/UnifiedLog/tracev3_file.py#L56 and will likely result in corresponding format strings not to be handled correctly

**Comment by Schramp** [comment]
Would you suggest removing the length requirement?

**Comment by Schramp** [comment]
https://github.com/Schramp/UnifiedLogReader/pull/3

**Comment by joachimmetz** [comment]
> Would you suggest removing the length requirement?

the con is that parsing the format strings might be more expensive, the pro is that this will parse format strings that exceed the limit, I've set the limit to 128 for now, but this is an arbitrary limit

**Comment by Schramp** [comment]
Fixed @Schramp
