### ISSUE TITLE
Dependencies are not installed by pip

### ISSUE THREAD

**Issue by ydkhatri** [ydkhatri/UnifiedLogReader#7]
`pip install unifiedlog` does not install the dependencies. Need to add _install-requires_ to setup.py.

**Comment by joachimmetz** [comment]
This is correct, if you want this you can add install_requires to your setup.py. Here is a write up of the tradeoffs https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by joachimmetz** [comment]
If you do plan to add it to setup.py I recommend to have it read them from requirements.txt, it is easier to control python2 or python3 only dependencies from there.

**Comment by ydkhatri** [comment]
Sure, I knew this was your intent. That is dev-friendly. But I also believe the library must be user-friendly, easy to install and use. 

Is there a way to have setup.py read from requirements.txt? I mean a built-in one liner instead of calling file open() and read() from within the setup.py code?

**Comment by joachimmetz** [comment]
> Is there a way to have setup.py read from requirements.txt? I mean a built-in one liner instead of calling file open() and read() from within the setup.py code?

yes, e.g. https://github.com/google/timesketch/blob/master/setup.py#L61

**Comment by ydkhatri** [comment]
Great! Will look into it.

**Comment by ydkhatri** [comment]
How do you generate a distribution package? When I use `python setup.py sdist`, it generates one without requirements.txt. 

When I include code for install_requires, it renames the file to requires.txt and adds it to egg-info folder. Is there a way this can be controlled?

**Comment by joachimmetz** [comment]
You should add it to MANIFEST.in e.g. `include requirements.txt`

E.g. https://github.com/google/timesketch/blob/master/MANIFEST.in

**Comment by ydkhatri** [comment]
I'm still trying to understand this. Is that what you did when you generated the distribution package? Because yours (one on pypi) does have that file, but the current MANIFEST.in does not include it. So did you use a different MANIFEST.in? I'm just trying to replicate your work first before making changes.

**Comment by joachimmetz** [comment]
I did not add it to MANIFEST.in. I just ran the commands described here: https://github.com/log2timeline/l2tdocs/blob/master/process/PyPI.md

**Comment by joachimmetz** [comment]
which version of setuptools are you using? (I need to look) maybe that makes a difference

**Comment by ydkhatri** [comment]
pip 9.0.3
setuptools  39.0.1

**Comment by joachimmetz** [comment]
setuptools 40.4.3

**Comment by ydkhatri** [comment]
I tried different versions of setuptools (including latest), and still can't get it to show up , without including it into MANIFEST.in 
So, I will just do that for now.
